### ISSUE TITLE
arm2pulumi: Not handling case-insensitivity correctly

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/arm2pulumi#1]
If I have a variable declared, as, say, "VNetName," ARM templates are case-insensitive and will work even if later I reference that variable as, say, "VnetName."
However, arm2pulumi fails when trying to convert an ARM template with those sorts of case changes.
It appears to be related to a virtual network name and/or related references.

An ARM template that demonstrates this can be provided on demand.

**Comment by mikhailshilkov** [comment]
The standalone arm2pulumi tool has been deprecated in favor of the [Pulumi CLI built-in command](https://www.pulumi.com/docs/cli/commands/pulumi_convert/) `pulumi convert --from arm`. Therefore, I'm closing all issues in this repository as "won't fix". Please file any issue related to `pulumi convert` in https://github.com/pulumi/pulumi/issues/
