### ISSUE TITLE
[Arm2pulumi] Add support for variable iteration

### ISSUE THREAD

**Issue by viveklak** [pulumi/arm2pulumi#10]
See https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/copy-variables
This will also require support for `copyIndex` template from pulumi/arm2pulumi#7.

Temporary workaround is to have users flatten the variables themselves in the desired programming language.

**Comment by mikhailshilkov** [comment]
The standalone arm2pulumi tool has been deprecated in favor of the [Pulumi CLI built-in command](https://www.pulumi.com/docs/cli/commands/pulumi_convert/) `pulumi convert --from arm`. Therefore, I'm closing all issues in this repository as "won't fix". Please file any issue related to `pulumi convert` in https://github.com/pulumi/pulumi/issues/
