### ISSUE TITLE
sub/nested resource names should not be composite (<parent>/<child>)

### ISSUE THREAD

**Issue by viveklak** [pulumi/arm2pulumi#13]
While arm templates use composite names e.g. `<parent name>/<child name>`, these are not legal when called in the API. Sub resources should be named with just the sub resource's name instead.

**Comment by mikhailshilkov** [comment]
The standalone arm2pulumi tool has been deprecated in favor of the [Pulumi CLI built-in command](https://www.pulumi.com/docs/cli/commands/pulumi_convert/) `pulumi convert --from arm`. Therefore, I'm closing all issues in this repository as "won't fix". Please file any issue related to `pulumi convert` in https://github.com/pulumi/pulumi/issues/
