### ISSUE TITLE
Incomplete Conversion of an App Service

### ISSUE THREAD

**Issue by haacked** [pulumi/arm2pulumi#14]
Hi! I tried to convert an App Service (Web App) that I exported from Azure Portal. It's not a particularly complicated site. When I ran the arm2pulumi tool, it gave me the warning about a partial conversion with the following message:

`configResource  no metadata found for resource type 'Microsoft.Web/sites/config' and version '2018-11-01'`

I also noticed that the code generated just sort of stops with the `WebApp`.

```csharp
SiteConfig = ,
```

The reason I call this out is I tried it earlier with a smaller site and it successfully generated code, but it did the same thing with `SiteConfig`.

**Comment by viveklak** [comment]
See #23 for the root cause.
