### ISSUE TITLE
Add test coverage of Azure Quickstart Templates

### ISSUE THREAD

**Issue by lukehoban** [pulumi/arm2pulumi#17]
Let's add the full set of Azure Quickstart Templates (https://github.com/Azure/azure-quickstart-templates) under test, with reporting on what percentage of quickstarts are passing conversion, and what the most common causes of failures are, so that we can use this to track completeness and progress.

**Comment by MisinformedDNA** [comment]
Also, it would cool to publish all the results to a new repo (pulumi-azure-quickstart-template) to quickly increase the number of examples.
