### ISSUE TITLE
Automate update for arm2pulumi on provider release

### ISSUE THREAD

**Issue by viveklak** [pulumi/arm2pulumi#19]

**Comment by stack72** [comment]
@viveklak what's needed here?

**Comment by mikhailshilkov** [comment]
The standalone arm2pulumi tool has been deprecated in favor of the [Pulumi CLI built-in command](https://www.pulumi.com/docs/cli/commands/pulumi_convert/) `pulumi convert --from arm`. Therefore, I'm closing all issues in this repository as "won't fix". Please file any issue related to `pulumi convert` in https://github.com/pulumi/pulumi/issues/
