### ISSUE TITLE
Generated string concatenation is not correct

### ISSUE THREAD

**Issue by MisinformedDNA** [pulumi/arm2pulumi#20]
Generated string concatenation should use `Output.Format()` when necessary

Repro:

Convert this ARM template:

```json
{  
	"$schema":"https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
	"contentVersion":"1.0.0.0",
	"parameters":{  
	   "ResourceNamePrefix":{  
		  "defaultValue":"[resourceGroup().name]",
		  "type":"string",
		  "metadata":{  
			 "description":"Prefix for resource names."
		  }
	   }
	},
	"resources":[  
	   {
		"type": "Microsoft.Storage/storageAccounts",
		"apiVersion": "2019-06-01",
		"name": "[concat(parameters('ResourceNamePrefix'),'storage')]",
		"location": "[resourceGroup().location]",
		"sku": {
			"name": "Standard_LRS",
			"tier": "Standard"
		},
		"kind": "Storage"
	  }
	]
  }
```

ACTUAL:

`[concat(parameters('ResourceNamePrefix'),'storage')]` is converted to `$"{resourceNamePrefixParam}storage"`

which results in something like `Output<T>storage`

EXPECTED:

`[concat(parameters('ResourceNamePrefix'),'storage')]` is converted to `Output.Format($"{resourceNamePrefixParam}storage")`

**Comment by mikhailshilkov** [comment]
The standalone arm2pulumi tool has been deprecated in favor of the [Pulumi CLI built-in command](https://www.pulumi.com/docs/cli/commands/pulumi_convert/) `pulumi convert --from arm`. Therefore, I'm closing all issues in this repository as "won't fix". Please file any issue related to `pulumi convert` in https://github.com/pulumi/pulumi/issues/
