### ISSUE TITLE
Consider removing `using AzureNextGen` alias

### ISSUE THREAD

**Issue by MisinformedDNA** [pulumi/arm2pulumi#21]
The converter adds 

```csharp
using AzureNextGen = Pulumi.AzureNextGen;
```

This shortens a lot of namespace qualifiers for a class, but it also makes moving all the namespaces to the top a little more annoying. 

Can we consider removing the `using AzureNextGen = Pulumi.AzureNextGen` from the top of generated files?

Assume the following generated code:

```csharp
var serverfarmResource = new AzureNextGen.Web.V20180201.AppServicePlan("serverfarmResource", new AzureNextGen.Web.V20180201.AppServicePlanArgs
{
    Location = resourceGroupVar.Apply(resourceGroupVar => resourceGroupVar.Location),
    Name = resourceGroupVar.Apply(resourceGroupVar => $"{resourceGroupVar.Name}-rotation-fnapp-plan"),
    ResourceGroupName = resourceGroupNameParam,
    Sku = new AzureNextGen.Web.V20180201.Inputs.SkuDescriptionArgs
    {
        Name = appServiceSKUVar,
    },
});
```

Current Steps:

1. Copy `AzureNextGen.Web.V20180201` from the first class initializers (i.e. `new AzureNextGen.Web.V20180201.AppServicePlan`)
1. Add `using AzureNextGen.Web.V20180201;` to the top of the file.
1. ERROR:  The type or namespace name 'AzureNextGen' could not be found
1. Prepend `Pulumi` to get `using Pulumi.AzureNextGen.Web.V20180201;`
1. Go to the previously used `AppServicePlan` class initializer and use the light bulb to simplify name
1. NOTE: None of the other namespaces can be automatically simplified
1. Find all other initializers and remove all the `AzureNextGen.Web.V20181101` namespaces

Desired Steps:

Assume:
```csharp
//using static AzureNextGen;
```

1. Copy `Pulumi.AzureNextGen.Web.V20180201` from the first class initializers (i.e. `new Pulumi.AzureNextGen.Web.V20180201.AppServicePlan`)
1. Add `using Pulumi.AzureNextGen.Web.V20180201;` to the top of the file.
1. Go to any `AppServicePlan` (or `AppServicePlanArgs`) class initializer and use the light bulb to simplify name for the whole document

As you can see, this has decreased our number of steps from 7 to 3, but also it's turned from an O(n) manual operation to an O(1) manual operation, saving the developer a lot of keystrokes and wasted time.

This has the small disadvantage of making the namespaces longer in the actual code, but it also gives the developer more flexibility to easily use namespaces how they want.

**Comment by mikhailshilkov** [comment]
> using static AzureNextGen;

What's that? Do you mean `using AzureNextGen = Pulumi.AzureNextGen;`?

**Comment by MisinformedDNA** [comment]
> > using static AzureNextGen;
> 
> What's that? Do you mean `using AzureNextGen = Pulumi.AzureNextGen;`?

Sorry. Fixed.

**Comment by mikhailshilkov** [comment]
The standalone arm2pulumi tool has been deprecated in favor of the [Pulumi CLI built-in command](https://www.pulumi.com/docs/cli/commands/pulumi_convert/) `pulumi convert --from arm`. Therefore, I'm closing all issues in this repository as "won't fix". Please file any issue related to `pulumi convert` in https://github.com/pulumi/pulumi/issues/
