### ISSUE TITLE
Generated parameter expressions don't assign as expected

### ISSUE THREAD

**Issue by MisinformedDNA** [pulumi/arm2pulumi#22]
Generated parameter expressions, that involve use of `Output<T>`, never make use of the right side of the null coalesce operator.

```csharp
var functionAppNameParam = Output.Create(config.Get("functionAppNameParam")) 
    ?? resourceGroupVar.Apply(resourceGroupVar => $"{resourceGroupVar.Name}func");
```

This is wrong because `Output.Create()` can never be `null` and so the right side of the null coalesce operator can never be evaluated.

It actually needs to be

```csharp
var functionAppNameParam = config.Get("functionAppNameParam") is string functionAppNameParamString
    ? Output.Create(functionAppNameParamString) 
    : resourceGroupVar.Apply(resourceGroupVar => Output.Format($"{resourceGroupVar.Name}func"));
```

Example ARM template:

```json
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "functionAppName": {
            "defaultValue": "[concat(resourceGroup().name, 'func')]",
            "type": "String",
        },
    },
    "variables": {
        "someOtherName": "[parameters('functionAppName')]",
    },
    "resources": [
    ]
}
```

**Comment by MisinformedDNA** [comment]
Or alternatively, maybe we use `resourceGroupNameParam` instead of `resourceGroupVar.Name` which would result in much simpler (and more similar to what was actually in the ARM template) code:

```csharp
var functionAppNameParam = config.Get("functionAppNameParam")
    ?? $"{resourceGroupNameParam}func";
```

**Comment by mikhailshilkov** [comment]
The standalone arm2pulumi tool has been deprecated in favor of the [Pulumi CLI built-in command](https://www.pulumi.com/docs/cli/commands/pulumi_convert/) `pulumi convert --from arm`. Therefore, I'm closing all issues in this repository as "won't fix". Please file any issue related to `pulumi convert` in https://github.com/pulumi/pulumi/issues/
