### ISSUE TITLE
Error messages should be more contextual (line numbers on the template)

### ISSUE THREAD

**Issue by viveklak** [pulumi/arm2pulumi#25]
Currently the json parser used by the converter looses line number and context information. Retaining this is important to make error messages more actionable.

**Comment by mikhailshilkov** [comment]
The standalone arm2pulumi tool has been deprecated in favor of the [Pulumi CLI built-in command](https://www.pulumi.com/docs/cli/commands/pulumi_convert/) `pulumi convert --from arm`. Therefore, I'm closing all issues in this repository as "won't fix". Please file any issue related to `pulumi convert` in https://github.com/pulumi/pulumi/issues/
