### ISSUE TITLE
Non-deterministic result when translating certain inputs

### ISSUE THREAD

**Issue by hiteshboinpally** [pulumi/arm2pulumi#28]
Certain ARM template inputs seem to cause non-deterministic output when passed through the converter tool. Specifically, they either return a partial conversion (with the accompanying diagnostic message) or a fatal error (`detected cycle in <some>Resource`). Additionally, the specific diagnostic message sometimes varies between runs, as well as the resource the cycle is detected in.

Here are some example templates that cause this with some additional information based on manual trials done via [arm2pulumi](https://www.pulumi.com/arm2pulumi/).
- https://github.com/Azure/azure-quickstart-templates/tree/master/101-asev2-appservice-sql-vpngw
  - Sometimes gives partial conversions, sometimes give cycle error (using web UI for conversion)
  - Partial conversion diagnostics:
     ```
	vaultResource  NYI: 'subscription' not supported as yet
	vaultResource  NYI: 'resourceId' not supported as yet
	vaultResource  NYI: 'resourceId' not supported as yet
	serverResource  NYI: 'subscription' not supported as yet
	siteResource  NYI: 'resourceId' not supported as yet
	privateDbDnsZoneNameParam  NYI: 'environment' not supported as yet
	administratorResource  NYI: 'subscription' not supported as yet
	vmNameVar  NYI: 'substring' not supported as yet
	containerResource  no metadata found for resource type 'Microsoft.Storage/storageAccounts/blobServices/containers' and version '2019-06-01'
	configResource  no metadata found for resource type 'Microsoft.Web/sites/config' and version '2020-06-01'
	loginUserVar  NYI: 'substring' not supported as yet
     ```
  - Fatal error message: `detected cycle at serverfarmResource` or `detected cycle at siteResource`
- https://github.com/Azure/azure-quickstart-templates/tree/master/101-sql-logical-server
  - Sometimes gives partial conversions, sometimes give cycle error (using web UI for conversion)
  - Partial conversion diagnostics:
     ```
	subscriptionIdVar  NYI: 'subscription' not supported as yet
	uniqueStorageVar  NYI: 'uniqueString' not supported as yet
	storageNameVar  NYI: 'tolower' not supported as yet
	vulnerabilityAssessmentResource  NYI: 'if' not supported as yet
	storageBlobContributorVar  NYI: 'subscriptionResourceId' not supported as yet
	securityAlertPolicyResource  no metadata found for resource type 'Microsoft.Sql/servers/securityAlertPolicies' and version '2020-02-02-preview'
	serverNameParam  NYI: 'uniqueString' not supported as yet
	uniqueRoleGuidVar  NYI: 'guid' not supported as yet
	serverResource  NYI: 'if' not supported as yet
	serverResource  NYI: 'if' not supported as yet
	roleAssignmentResource  NYI: 'resourceId' not supported as yet
	connectionPolicyResource  no metadata found for resource type 'Microsoft.Sql/servers/connectionPolicies' and version '2014-04-01'
     ```
  - Fatal error message: `detected cycle at vulnerabilityAssessmentResource`
- https://github.com/Azure/azure-quickstart-templates/tree/master/101-redis-cache 
  - Sometimes gives partial conversions, sometimes give cycle error (using web UI for conversion)
  - Partial conversion diagnostics: `diagnosticsettingResource  NYI: 'format' not supported as yet`
      - Still occasionally got cycle fatal error when that `'format'` parameter was removed
      - All conversion errors (including fatal) disappeared if that resource was removed completely though (not sure about resulting code compiling, etc.)
  - Fatal error message: `detected cycle at diagnosticsettingResource`
- https://github.com/Azure/azure-quickstart-templates/tree/master/101-functions-managed-identity 
  - Sometimes gives partial conversions, sometimes give cycle error (using web UI for conversion)
  - Partial conversion diagnostics:
     ```
	siteResource  NYI: 'environment' not supported as yet
	siteResource  NYI: 'environment' not supported as yet
	siteResource  NYI: 'toLower' not supported as yet
	siteResource  NYI: 'resourceId' not supported as yet
	componentResource  NYI: 'environment' not supported as yet
	storageAccountNameVar  NYI: 'uniquestring' not supported as yet
	functionAppNameParam  NYI: 'uniqueString' not supported as yet
	principalIdOut  NYI: 'resourceId' not supported as yet
     ```
   - Fatal error message: `detected cycle at siteResource`
- https://github.com/Azure/azure-quickstart-templates/tree/master/101-custom-rp-with-function
  - Sometimes gives partial conversions, sometimes give cycle error (using web UI for conversion)
  - Partial conversion diagnostics:
     ```
	funcNameParam  NYI: 'uniqueString' not supported as yet
	storageAccountNameParam  NYI: 'uniqueString' not supported as yet
	siteResource  NYI: 'listKeys' not supported as yet
	siteResource  NYI: 'toLower' not supported as yet
	siteResource  NYI: 'uri' not supported as yet
	resourceProviderResource  NYI: 'listSecrets' not supported as yet
	customResourceResource  no metadata found for resource type 'Microsoft.CustomProviders/resourceProviders/customResources' and version '2018-09-01-preview'
     ```
 - Fatal error message: `detected cycle at resourceProviderResource`

**Comment by mikhailshilkov** [comment]
The standalone arm2pulumi tool has been deprecated in favor of the [Pulumi CLI built-in command](https://www.pulumi.com/docs/cli/commands/pulumi_convert/) pulumi convert --from arm. Therefore, I'm closing all issues in this repository as "won't fix". Please file any issue related to pulumi convert in https://github.com/pulumi/pulumi/issues/
