### ISSUE TITLE
arm2pulumi doesn't handle parameters in Deployment resource

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/arm2pulumi#29]
Trying to import `Microsoft.Resources/deployments` and it's not handling the `Parameters` input (https://www.pulumi.com/docs/reference/pkg/azure-native/resources/deployment/#parameters_csharp)

ARM docs: https://docs.microsoft.com/en-us/azure/templates/microsoft.resources/deployments?tabs=json#deploymentproperties-object

**Comment by Martvdjagt** [comment]
The issue reported above was solved for me by using the below syntax.
var parameters = new Dictionary<string, object>
        {
            { "name", new Dictionary<string, object>() { { "value", apiWebsiteName } } }
        };

Suggestions for improvement:
* Add a code sample to documentation 
* Fix the conversion of parameters section in the arm2pulumi tool.

**Comment by mikhailshilkov** [comment]
The standalone arm2pulumi tool has been deprecated in favor of the [Pulumi CLI built-in command](https://www.pulumi.com/docs/cli/commands/pulumi_convert/) pulumi convert --from arm. Therefore, I'm closing all issues in this repository as "won't fix". Please file any issue related to pulumi convert in https://github.com/pulumi/pulumi/issues/
