### ISSUE TITLE
arm2pulumi v2 fails for explicit versions of types

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/arm2pulumi#33]
Disabled [template test](https://github.com/pulumi/pulumi-azure-native/blob/27b5d7a6d2430f7f68acb15bace3ef3a84db8aec/provider/pkg/arm2pulumi/internal/test/templates_test.go#L42) for `testdata/templates/quickstart/storageAccount.json` for `go` fails with:

```diff
@@ -33,3 +33,3 @@
                        ResourceGroupName: pulumi.String(resourceGroupNameParam),
-                       Sku: &storage.SkuArgs{
+                       Sku: &v20210201.SkuArgs{
                                Name: pulumi.String(storageAccountTypeParam),
```

**Comment by mikhailshilkov** [comment]
The standalone arm2pulumi tool has been deprecated in favor of the [Pulumi CLI built-in command](https://www.pulumi.com/docs/cli/commands/pulumi_convert/) pulumi convert --from arm. Therefore, I'm closing all issues in this repository as "won't fix". Please file any issue related to pulumi convert in https://github.com/pulumi/pulumi/issues/
