### ISSUE TITLE
Update hosted arm2pulumi or at least put an info banner there

### ISSUE THREAD

**Issue by mnlumi** [pulumi/arm2pulumi#34]
Add a note that 'arm2pulumi is still using v1 of the provider. If you want to use v2, please use the command line.'

**Comment by lukehoban** [comment]
Should we instead just get it working with v2?

**Comment by mnlumi** [comment]
@lukehoban Yes, getting it working with v2 is certainly the preferred and ultimate goal. The banner is meant to be an intermediate step while awaiting prioritization of arm2pulumi fixes. cc @mikhailshilkov

**Comment by mikhailshilkov** [comment]
The standalone arm2pulumi tool has been deprecated in favor of the [Pulumi CLI built-in command](https://www.pulumi.com/docs/cli/commands/pulumi_convert/) pulumi convert --from arm. Therefore, I'm closing all issues in this repository as "won't fix". Please file any issue related to pulumi convert in https://github.com/pulumi/pulumi/issues/
