### ISSUE TITLE
arm2pulumi Various issues converting CDN-oriented ARM template to typescript

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/arm2pulumi#35]
How to recreate:
Convert this ARM template to pulumi typescript
https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-cdn-with-ruleseengine-rewriteandredirect/azuredeploy.json

The generated code will have a few "compile" time issue and a run time issue.

"compile" time issues:

- The deliveryPolicy section uses `"@odata.type"` as the property name when it should be `odataType` 
- The deliveryPolicy section uses strings for the `order` property value when it should be a number.
- The generated code creates a profile resource but doesn't reference it in the endpoint resource. 

"run" time issue

- The generated code sets the endpoint name to `\`${profileNameParam}/${endpointNameParam}\`` but Azure doesn't appear to like this naming convention. Using just `endpointNameParam` works.

I've attached a copy of the generated code with the corrections (and a few other changes I made for testing purposes).
[index_ts.txt](https://github.com/pulumi/pulumi-azure-nextgen-provider/files/5394282/index_ts.txt)

**Comment by mikhailshilkov** [comment]
The standalone arm2pulumi tool has been deprecated in favor of the [Pulumi CLI built-in command](https://www.pulumi.com/docs/cli/commands/pulumi_convert/) `pulumi convert --from arm`. Therefore, I'm closing all issues in this repository as "won't fix". Please file any issue related to `pulumi convert` in https://github.com/pulumi/pulumi/issues/
