### ISSUE TITLE
[Arm2pulumi] Improve template function coverage

### ISSUE THREAD

**Issue by viveklak** [pulumi/arm2pulumi#7]
Add support for the following template functions:

- [x] `resourceId`
- [ ] `subscription`
- [ ] `listKeys`
- [ ] `uri`

- [ ] String functions
  - [ ] `uniqueString`
  - [ ] `toLower`
  - [ ] `newGuid`

- [ ] Conversion functions:
  - [ ] `convertToArray`
  - [ ] `json`

**Comment by nesl247** [comment]
This is definitely a pain point right now when trying to setup the Azure/Datadog log forwarding. Having this missing means a lot more manual work must be done.

**Comment by mikhailshilkov** [comment]
The standalone arm2pulumi tool has been deprecated in favor of the [Pulumi CLI built-in command](https://www.pulumi.com/docs/cli/commands/pulumi_convert/) `pulumi convert --from arm`. Therefore, I'm closing all issues in this repository as "won't fix". Please file any issue related to `pulumi convert` in https://github.com/pulumi/pulumi/issues/
