### ISSUE TITLE
[arm2pulumi] Empty objects are not converted to anything

### ISSUE THREAD

**Issue by MisinformedDNA** [pulumi/arm2pulumi#8]
Take the following example ARM resource:

```json
{
	"apiVersion": "2015-05-01",
	"name": "ExampleAppName",
	"type": "microsoft.insights/components",
	"location": "centralus",
	"tags": {},
	"properties": {
		"ApplicationId": "[parameters('name')]",
		"Request_Source": "IbizaWebAppExtensionCreate"
	}
}
```

When converted, it results as:

```csharp
var exampleAppName = Component("exampleAppName", new ComponentArgs
{
	Location = "centralus",
	RequestSource = "IbizaWebAppExtensionCreate",
	ResourceGroupName = resourceGroupNameParam,
	ResourceName = "ExampleAppName",
	Tags = ,
});
```

It should probably be

```csharp
Tags = { },
```

**Comment by mikhailshilkov** [comment]
The standalone arm2pulumi tool has been deprecated in favor of the [Pulumi CLI built-in command](https://www.pulumi.com/docs/cli/commands/pulumi_convert/) `pulumi convert --from arm`. Therefore, I'm closing all issues in this repository as "won't fix". Please file any issue related to `pulumi convert` in https://github.com/pulumi/pulumi/issues/
